### ISSUE TITLE
Unable to start video source

### ISSUE THREAD

**Issue by MadalenaSousa** [imadtoubal/Emotion-Recognition-with-ML5#2]
Hi! 

I've been getting an error on the inspector consolo saying: "DOMException: Could not start video source", even when I open the github pages link that is available in the repository info.
This results in the camera not being activated when opening the code.

Is this something that is wrong with my computer or something that I'm doing? any ideia on what it is?

Thank you in advance

**Comment by imadtoubal** [comment]
Hi Madelena, 

Are you sure you enabled camera access on your browser?

Kind regards.

**Comment by MadalenaSousa** [comment]
Hey! Reinstalled my camera drivers and it worked. Ty, sry for bothering
